name = "javascript_date"
version = "1.0.0"
target = "javascript"
licences = ["GPL-3.0-only"]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_javascript = "~> 0.8"

[dev-dependencies]
gleeunit = "~> 1.0"
